# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fca93b16f052898f6ae7a4fb444fbfad45dfec53eadaaf15290c30e985fc32b1260fd3032e7f080926bb345d7e5530ae88448e81812b1972544cb73e13d81f5f

test:
  secret_key_base: 2c7030410cf206503c7675755957fcf2e5edc3ac2b7be3712b6ac9fb0127b09269283f8c0c7dcb03ec1d30b87e4a356f7e6abe9ef44f07aeaa79efee6ab22b3b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
